### ISSUE TITLE
Add OpenAI and chatGPT t sites 

### ISSUE THREAD

**Issue by SlimRG** [onminonA/proxy.pac#1]

**Comment by SlimRG** [comment]
https://raw.githubusercontent.com/onminonA/proxy.pac/main/proxy_yt.pac

**Comment by onminonA** [comment]
Sites OpenAI and chatGPT are in the PAC file. For more information - https://github.com/onminonA/proxy.pac/wiki/(firefox_)proxy(_yt).pac#en---ru
